server:
  port: 8080
spring:
  application:
    name: "crediya-loan-application-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/loan-applications"
    usersById: "/api/v1/loan-applications"/{id}"

adapters:
  r2dbc:
    host: "db.zpedtzxkdhkuvvpxbkdg.supabase.co"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "authentication123"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html